# Generated by Django 5.0.4 on 2024-05-03 16:41

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published')], default='draft', max_length=20)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='TelegramChennels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100, null=True)),
                ('channel_username', models.CharField(max_length=100, null=True)),
                ('chenel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('has_access', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'telegram_chennels',
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medias')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='main.post')),
            ],
            options={
                'db_table': 'postmedias',
            },
        ),
        migrations.CreateModel(
            name='PlannedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_posting', models.DateTimeField()),
                ('was_posted', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_posts', to='main.post')),
                ('chennals', models.ManyToManyField(related_name='planned_posts', to='main.telegramchennels')),
            ],
            options={
                'db_table': 'planned_posts',
            },
        ),
    ]
