# Generated by Django 5.0.6 on 2024-05-11 20:10

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_plannedposts_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedposts',
            options={'verbose_name': 'Планируемая публикация', 'verbose_name_plural': 'Планируемые публикации'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='postmedia',
            options={'verbose_name': 'Медиафайл публикации', 'verbose_name_plural': 'Медиафайл публикаций'},
        ),
        migrations.AlterModelOptions(
            name='telegramchennels',
            options={'verbose_name': 'Телеграм-канал', 'verbose_name_plural': 'Telegram-каналы'},
        ),
        migrations.RemoveField(
            model_name='plannedposts',
            name='was_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='telegramchennels',
            name='chenel_id',
        ),
        migrations.RemoveField(
            model_name='telegramchennels',
            name='has_access',
        ),
        migrations.AlterField(
            model_name='plannedposts',
            name='chennals',
            field=models.ManyToManyField(related_name='planned_posts', to='main.telegramchennels', verbose_name='каналы'),
        ),
        migrations.AlterField(
            model_name='plannedposts',
            name='count_max_posts',
            field=models.IntegerField(default=1, verbose_name='Общее количество запусков'),
        ),
        migrations.AlterField(
            model_name='plannedposts',
            name='datetime_posting',
            field=models.DateTimeField(verbose_name='Дата и время отправки публикации'),
        ),
        migrations.AlterField(
            model_name='plannedposts',
            name='interval',
            field=models.CharField(choices=[('', '----------'), ('every_5_minutes', 'Каждые 5 минут'), ('every_10_minutes', 'Каждые 10 минут'), ('every_15_minutes', 'Каждые 15 минут'), ('every_20_minutes', 'Каждые 20 минут'), ('every_30_minutes', 'Каждые 30 минут'), ('every_1_hours', 'Каждый 1 час'), ('every_2_hours', 'Каждые 2 часа'), ('every_3_hours', 'Каждые 3 часа')], default='', max_length=20, verbose_name='Интервал'),
        ),
        migrations.AlterField(
            model_name='plannedposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_posts', to='main.post', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('album', 'Альбом')], default='text', max_length=20, verbose_name='Тип публикации'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to='medias', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_type',
            field=models.CharField(choices=[('video', 'Видео'), ('image', 'Изображение')], default='image', max_length=20, verbose_name='Тип медиафайла'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='main.post', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='telegramchennels',
            name='channel_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название канала'),
        ),
        migrations.AlterField(
            model_name='telegramchennels',
            name='channel_username',
            field=models.CharField(max_length=100, null=True, verbose_name='Название канала(username)'),
        ),
    ]
