# Generated by Django 5.0.6 on 2024-05-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_plannedposts_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedposts',
            name='interval',
            field=models.CharField(choices=[('1', '----------'), ('every_1_minutes', 'Каждые 1 минут'), ('every_5_minutes', 'Каждые 5 минут'), ('every_10_minutes', 'Каждые 10 минут'), ('every_15_minutes', 'Каждые 15 минут'), ('every_20_minutes', 'Каждые 20 минут'), ('every_30_minutes', 'Каждые 30 минут'), ('every_1_hours', 'Каждый 1 час'), ('every_2_hours', 'Каждые 2 часа'), ('every_3_hours', 'Каждые 3 часа')], default='1', max_length=20, verbose_name='Интервал'),
        ),
    ]
