# Generated by Django 5.0.6 on 2024-05-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_plannedposts_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedposts',
            name='count_max_posts',
        ),
        migrations.AddField(
            model_name='plannedposts',
            name='end_datetime_posting',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает'),
        ),
        migrations.AddField(
            model_name='plannedposts',
            name='one_time_task',
            field=models.BooleanField(default=True, verbose_name='Одноразовая задача'),
        ),
    ]
