# Generated by Django 5.0.6 on 2024-10-06 17:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_telegramchennels_channel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Код публикация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Текст'),
        ),
    ]
